<?php
/**
 * File defining the settings for the Foxway extension.
 * More info can be found at https://www.mediawiki.org/wiki/Extension:Foxway
 *
 *						  NOTICE:
 * Changing one of these settings can be done by copieng or cutting it,
 * and placing it in LocalSettings.php, AFTER the inclusion of Foxway.
 *
 * @file Settings.php
 * @ingroup Foxway
 * @author Pavel Astakhov <pastakhov@yandex.ru>
 */

// Check to see if we are being called as an extension or directly
if ( !defined( 'MEDIAWIKI' ) ) {
	die( 'This file is an extension to MediaWiki and thus not a valid entry point.' );
}

// Default settings


/**
 * You can specify the namespaces in which is allowed to use the extension Foxway.
 *
 * Thus it is possible to give permission to use this extension is just a special user group, example:
 * define("NS_PHP", 1000);
 * define("NS_PHP_TALK", 1001);
 * $wgExtraNamespaces[NS_PHP] = "PHP";
 * $wgExtraNamespaces[NS_PHP_TALK] = "PHP_Talk";
 *
 * $wgNamespacesWithFoxway = array( NS_PHP );
 * $wgNamespaceProtection[NS_PHP] = array( 'php_editor' );
 * $wgGroupPermissions['sysop']['php_editor'] = true;
 *
 * @var array Namespaces in which is allowed to use the extension Foxway, boolean 'true' for unlimited
 */
$wgNamespacesWithFoxway = true;

$wgFoxwayFunctions = array(
	'FVariable' => array( // Variable handling Functions @see http://www.php.net/manual/en/ref.var.php
		'boolval',
		//'debug_zval_dump',
		'doubleval',
		'empty',
		'floatval',
		'get_defined_vars', //implemented in Runtime.php
		//'get_resource_type',
		'gettype',
		//'import_request_variables', @todo  need hide not foxway Cookie
		'intval',
		'is_array',
		'is_bool',
		//'is_callable',
		'is_double',
		'is_float',
		'is_int',
		'is_integer',
		'is_long',
		'is_null',
		'is_numeric',
		//'is_object',
		'is_real',
		//'is_resource',
		'is_scalar',
		'is_string',
		'isset',
		'print_r',
		//'serialize',
		'settype',
		'strval',
		//'unserialize',
		'unset',
		'var_dump',
		'var_export',
	),
	'FArray' => array( // Array Functions @see http://www.php.net/manual/en/ref.array.php
		'array_change_key_case',
		'array_chunk',
		//'array_column', @todo PHP 5 >= 5.5.0
		'array_combine',
		'array_count_values',
		'array_diff_assoc',
		'array_diff_key',
		'array_diff',
		'array_fill_keys',
		'array_fill',
		'array_flip',
		'array_intersect_assoc',
		'array_intersect_key',
		'array_intersect',
		'array_key_exists',
		'array_keys',
		'array_merge_recursive',
		'array_merge',
		'array_multisort',
		'array_pad',
		'array_pop',
		'array_product',
		'array_push',
		'array_rand',
		'array_replace_recursive',
		'array_replace',
		'array_reverse',
		'array_search',
		'array_shift',
		'array_slice',
		'array_splice',
		'array_sum',
		'array_unique',
		'array_unshift',
		'array_values',
		'arsort',
		'asort',
		'count',
		'current',
		'each',
		'end',
		'in_array',
		'key',
		'krsort',
		'ksort',
		'natcasesort',
		'natsort',
		'next',
		'pos',
		'prev',
		'range',
		'reset',
		'rsort',
		'shuffle',
		'sizeof',
		'sort',
	),
	'FString' => array( // String Functions @see http://www.php.net/manual/en/ref.strings.php
		'addcslashes',
		'addslashes',
		'chop',
		'chr',
		'chunk_split',
		'convert_cyr_string',
		'convert_uudecode',
		'convert_uuencode',
		'count_chars',
		'crc32',
		'crypt',
		'explode',
		'html_entity_decode',
		'htmlentities',
		'htmlspecialchars_decode',
		'htmlspecialchars',
		'implode',
		'join',
		'lcfirst',
		'levenshtein',
		'ltrim',
		'md5',
		'metaphone',
		'money_format',
		'nl_langinfo',
		'nl2br',
		'number_format',
		'ord',
		'printf',
		'quotemeta',
		'rtrim',
		'sha1',
		'similar_text',
		'soundex',
		'sprintf',
		'sscanf',
		'str_ireplace',
		'str_pad',
		'str_repeat',
		'str_replace',
		'str_rot13',
		'str_shuffle',
		'str_split',
		'str_word_count',
		'strcasecmp',
		'strchr',
		'strcmp',
		'strcspn',
		'strip_tags',
		'stripcslashes',
		'stripos',
		'stripslashes',
		'stristr',
		'strlen',
		'strnatcasecmp',
		'strnatcmp',
		'strncmp',
		'strpbrk',
		'strpos',
		'strrchr',
		'strrev',
		'strripos',
		'strrpos',
		'strspn',
		'strstr',
		'strtok',
		'strtolower',
		'strtoupper',
		'strtr',
		'substr_compare',
		'substr_count',
		'substr_replace',
		'substr',
		'trim',
		'ucfirst',
		'ucwords',
		'vprintf',
		'vsprintf',
		'wordwrap',
	),
	'Fpcre' => array( // PCRE Functions @see http://php.net/manual/en/ref.pcre.php
		'preg_filter',
		'preg_grep',
		'preg_last_error',
		'preg_match_all',
		'preg_match_all',
		'preg_match',
		'preg_quote',
		//'preg_replace', not tested
		'preg_split',
	),
	'FMath' => array( // Math Functions @see http://www.php.net/manual/en/ref.math.php
		'abs',
		'acos',
		'acosh',
		'asin',
		'asinh',
		'atan2',
		'atan',
		'atanh',
		'base_convert',
		'bindec',
		'ceil',
		'cos',
		'cosh',
		'decbin',
		'dechex',
		'decoct',
		'deg2rad',
		'exp',
		'expm1',
		'floor',
		'fmod',
		'getrandmax',
		'hexdec',
		'hypot',
		'is_finite',
		'is_infinite',
		'is_nan',
		'lcg_value',
		'log10',
		'log1p',
		'log',
		'max',
		'min',
		'mt_getrandmax',
		'mt_rand',
		'mt_srand',
		'octdec',
		'pi',
		'pow',
		'rad2deg',
		'rand',
		'round',
		'sin',
		'sinh',
		'sqrt',
		'srand',
		'tan',
		'tanh',
	),
);

$wgFoxwayAllowedPHPConstants = array(
	'CASE_UPPER',
	'CASE_LOWER',
	'SORT_ASC',
	'SORT_DESC',
	'SORT_REGULAR',
	'SORT_NUMERIC',
	'SORT_STRING',
	'SORT_LOCALE_STRING',
	'SORT_NATURAL', // PHP >= 5.4.0
	'SORT_FLAG_CASE', // PHP >= 5.4.0
	'COUNT_RECURSIVE',
	'CRYPT_STD_DES',
	'CRYPT_EXT_DES',
	'CRYPT_MD5',
	'CRYPT_BLOWFISH',
	'CRYPT_SHA256',
	'CRYPT_SHA512',
	'ENT_COMPAT',
	'ENT_QUOTES',
	'ENT_NOQUOTES',
	'ENT_HTML401', // PHP >= 5.4.0
	'ENT_XML1', // PHP >= 5.4.0
	'ENT_XHTML', // PHP >= 5.4.0
	'ENT_HTML5', // PHP >= 5.4.0
	'ENT_IGNORE',
	'ENT_SUBSTITUTE', // PHP >= 5.4.0
	'ENT_DISALLOWED', // PHP >= 5.4.0
	'STR_PAD_RIGHT',
	'STR_PAD_LEFT',
	'STR_PAD_BOTH',
	'ABDAY_1',
	'ABDAY_2',
	'ABDAY_3',
	'ABDAY_4',
	'ABDAY_5',
	'ABDAY_6',
	'ABDAY_7',
	'DAY_1',
	'DAY_2',
	'DAY_3',
	'DAY_4',
	'DAY_5',
	'DAY_6',
	'DAY_7',
	'ABMON_1',
	'ABMON_2',
	'ABMON_3',
	'ABMON_4',
	'ABMON_5',
	'ABMON_6',
	'ABMON_7',
	'ABMON_8',
	'ABMON_9',
	'ABMON_10',
	'ABMON_11',
	'ABMON_12',
	'MON_1',
	'MON_2',
	'MON_3',
	'MON_4',
	'MON_5',
	'MON_6',
	'MON_7',
	'MON_8',
	'MON_9',
	'MON_10',
	'MON_11',
	'MON_12',
	'AM_STR',
	'PM_STR',
	'D_T_FMT',
	'D_FMT',
	'T_FMT',
	'T_FMT_AMPM',
	'ERA',
	'ERA_YEAR',
	'ERA_D_T_FMT',
	'ERA_D_FMT',
	'ERA_T_FMT',
	'INT_CURR_SYMBOL',
	'CURRENCY_SYMBOL',
	'CRNCYSTR',
	'MON_DECIMAL_POINT',
	'MON_THOUSANDS_SEP',
	'MON_GROUPING',
	'POSITIVE_SIGN',
	'NEGATIVE_SIGN',
	'INT_FRAC_DIGITS',
	'FRAC_DIGITS',
	'P_CS_PRECEDES',
	'P_SEP_BY_SPACE',
	'N_CS_PRECEDES',
	'N_SEP_BY_SPACE',
	'P_SIGN_POSN',
	'N_SIGN_POSN',
	'DECIMAL_POINT',
	'RADIXCHAR',
	'THOUSANDS_SEP',
	'THOUSEP',
	'GROUPING',
	'YESEXPR',
	'NOEXPR',
	'YESSTR',
	'NOSTR',
	'CODESET',
	// @see http://www.php.net/manual/en/pcre.constants.php
	'PREG_PATTERN_ORDER',
	'PREG_SET_ORDER',
	'PREG_OFFSET_CAPTURE',
	'PREG_SPLIT_NO_EMPTY',
	'PREG_SPLIT_DELIM_CAPTURE',
	'PREG_SPLIT_OFFSET_CAPTURE',
	'PREG_NO_ERROR',
	'PREG_INTERNAL_ERROR',
	'PREG_BACKTRACK_LIMIT_ERROR',
	'PREG_RECURSION_LIMIT_ERROR',
	'PREG_BAD_UTF8_ERROR',
	'PREG_BAD_UTF8_OFFSET_ERROR',
	'PCRE_VERSION',
	'PREG_GREP_INVERT',
	// @see http://www.php.net/manual/en/math.constants.php
	'M_PI',
	'M_E',
	'M_LOG2E',
	'M_LOG10E',
	'M_LN2',
	'M_LN10',
	'M_PI_2',
	'M_PI_4',
	'M_1_PI',
	'M_2_PI',
	'M_SQRTPI',
	'M_2_SQRTPI',
	'M_SQRT2',
	'M_SQRT3',
	'M_SQRT1_2',
	'M_LNPI',
	'M_EULER',
	'PHP_ROUND_HALF_UP',
	'PHP_ROUND_HALF_DOWN',
	'PHP_ROUND_HALF_EVEN',
	'PHP_ROUND_HALF_ODD',
	'NAN',
	'INF',
	'PHP_INT_MAX',
	'PHP_INT_SIZE',
);
