<?php

namespace Foxway;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-28 at 05:28:38.
 */
class InterpreterTest extends \PHPUnit_Framework_TestCase {

	public function testRun_echo_apostrophe() {
		$this->assertEquals(
				Interpreter::run('echo "Hello!";'),
				'Hello!'
				);
	}

	public function testRun_echo_quotes() {
		$this->assertEquals(
				Interpreter::run("echo 'Hello!';"),
				'Hello!'
				);
	}

	public function testRun_echo_union() {
		$this->assertEquals(
				Interpreter::run('echo "String" . "Union";'),
				'StringUnion'
				);
		$this->assertEquals(
				Interpreter::run('echo \'This \' . \'string \' . \'was \' . \'made \' . \'with concatenation.\' . "\n";'),
				"This string was made with concatenation.\n"
				);
	}

	public function testRun_echo_parameters() {
		$this->assertEquals(
				Interpreter::run('echo "Parameter1","Parameter2" , "Parameter3";'),
				'Parameter1Parameter2Parameter3'
				);
		$this->assertEquals(
				Interpreter::run('echo \'This \', \'string \', \'was \', \'made \', \'with multiple parameters.\';'),
				'This string was made with multiple parameters.'
				);
	}

	public function testRun_echo_multiline() {
		$this->assertEquals(
				Interpreter::run('echo "This spans
multiple lines. The newlines will be
output as well";'),
				"This spans\nmultiple lines. The newlines will be\noutput as well"
				);
		$this->assertEquals(
				Interpreter::run('echo "Again: This spans\nmultiple lines. The newlines will be\noutput as well.";'),
				"Again: This spans\nmultiple lines. The newlines will be\noutput as well."
				);
	}

	public function testRun_echo_variables() {
		$this->assertEquals(
				Interpreter::run('
$foo = "foobar";
$bar = "barbaz";
echo "foo is $foo"; // foo is foobar'),
				'foo is foobar'
				);
		$this->assertEquals(
				Interpreter::run('echo "foo is {$foo}";'),
				'foo is foobar'
				);
		$this->assertEquals(
				Interpreter::run('echo "foo is {$foo}.";'),
				'foo is foobar.'
				);
		$this->assertEquals(
				Interpreter::run('echo "foo is $foo\n\n";'),
				"foo is foobar\n\n"
				);
		$this->assertEquals(
				Interpreter::run('echo \'foo is $foo\';'),
				'foo is $foo'
				);
		$this->assertEquals(
				Interpreter::run('echo $foo,$bar;'),
				'foobarbarbaz'
				);
		$this->assertEquals(
				Interpreter::run('echo "$foo$bar";'),
				'foobarbarbaz'
				);
		$this->assertEquals(
				Interpreter::run('echo "s{$foo}l{$bar}e";'),
				'sfoobarlbarbaze'
				);
		$this->assertEquals(
				Interpreter::run('echo "s{$foo}l$bar";'),
				'sfoobarlbarbaz'
				);
		$this->assertEquals(
				Interpreter::run('echo "start" . $foo . "end";'),
				'startfoobarend'
				);
		$this->assertEquals(
				Interpreter::run('echo "This ", \'string \', "was $foo ", \'with multiple parameters.\';'),
				'This string was foobar with multiple parameters.'
				);
	}

	public function testRun_echo_escaping() {
		$this->assertEquals(
				Interpreter::run('echo \'s\\\\\\\'e\';'),	// echo 's\\\'e';
				's\\\'e'									// s\'e
				);
		$this->assertEquals(
				Interpreter::run('echo "s\\\\\\"e";'),	// echo "s\\\"e";
				's\\"e'									// s\"e
				);
	}

	public function testRun_echo_digit() {
		$this->assertEquals(
				Interpreter::run('echo 5;'),
				'5'
				);
	}

	public function testRun_echo_math() {
		$this->assertEquals(
				Interpreter::run('echo 5 + 5 * 10;'),
				'55'
				);
		$this->assertEquals(
				Interpreter::run('echo 5 + 5 / 10 + 50/100;'),
				'6'
				);
		$this->assertEquals(
				Interpreter::run('echo 10 * 10 + "20" * \'20\' - 30 * 30 + 40 / 9;'),
				'-395.55555555556'
				);
	}

	public function testRun_echo_math_params() {
		$this->assertEquals(
				Interpreter::run('echo \'10 + 5 * 5 = \', 10 + 5 * 5, "\n\n";'),
				"10 + 5 * 5 = 35\n\n"
				);
	}

	public function testRun_echo_math_variables() {
		$this->assertEquals(
				Interpreter::run('
$foo = 100;
$bar = \'5\';
echo "\$foo * \$bar = $foo * $bar = ", $foo * $bar, "\n\n";'),
				"\$foo * \$bar = 100 * 5 = 500\n\n"
				);
		$this->assertEquals(
				Interpreter::run('echo "\$foo / \$bar = $foo / $bar = ", $foo / $bar, "\n\n";'),
				"\$foo / \$bar = 100 / 5 = 20\n\n"
				);
	}
}
